export const MECHANISMS = [
  'Worker Placement',
  'Deck Building',
  'Engine Building',
  'Area Control',
  'Tile Laying',
  'Set Collection',
  'Route Building',
  'Push Your Luck',
  'Resource Management',
  'Action Selection',
  'Point Salad',
  'Cooperative',
  'Semi-Cooperative',
  'Legacy / Campaign',
  'Asymmetric',
  'Variable Player Powers',
  'Real-Time',
  'Hidden Role',
  'Social Deduction',
  'Bluffing',
  'Party Game',
  'Dexterity',
  'Dungeon Crawl',
  'Wargame / Combat',
  'Abstract Strategy',
  'Economic / Market',
  'Storytelling / Narrative',
]
